-- 010_tables.sql
-- ユーザーテーブル作成

USE DATABASE APP_DB;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID        NUMBER AUTOINCREMENT,
    USER_NAME      STRING NOT NULL,
    EMAIL          STRING,
    STATUS         STRING DEFAULT 'ACTIVE',
    CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT     TIMESTAMP_NTZ,

    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
);


CREATE TABLE IF NOT EXISTS USERS_DETAIL (
    USER_ID        NUMBER AUTOINCREMENT,
    USER_NAME      STRING NOT NULL,
    EMAIL          STRING,
    STATUS         STRING DEFAULT 'ACTIVE',
    CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT     TIMESTAMP_NTZ,

    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
);
